/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oczko;

import java.util.Random;

/**
 *
 * @author mariuszbugajski
 */
public class Gra extends javax.swing.JFrame {

    int pkt1, pkt2;
    
    Karta [] gracz1;
    Karta [] gracz2;
    
    /**
     * Creates new form Gra
     */
    public Gra() {
        initComponents();
        this.gracz1 = new Karta[7];
        this.gracz2 = new Karta[7];
        
        // Inicjalizacja talii gracza 1
        for (int i = 0; i < 7; i++){
            this.gracz1[i] = new Karta();
        }
        
        // Inicjalizacja talii komputera
        for (int i = 0; i < 7; i++){
            this.gracz1[i] = new Karta();
        }
        
        Random r = new Random();
        
        //karty gracza
        for(int i = 0; i < 2; i++){
            this.gracz1[i] = new Karta(r.nextInt());
            System.out.println(gracz1[i].wartosc);
        }
        
        // Karty komputera
        for(int i = 0; i < 2; i++){
            this.gracz2[i] = new Karta(r.nextInt());
            System.out.println(gracz2[i].wartosc);
        }
        
        this.printScreen();
    }
    
    void printScreen(){
        //Wyświetlanie kart komputera
        if(this.gracz1[0].typ == 0){
            jLabel1.setVisible(false);
        }else{
            jLabel1.setText(this.gracz1[0].wartosc + "");
        }
        
        if(this.gracz1[1].typ == 0){
            jLabel2.setVisible(false);
        }else{
            jLabel2.setText(this.gracz1[1].wartosc + "");
        }
        
        if(this.gracz1[2].typ == 0){
            jLabel3.setVisible(false);
        }else{
            jLabel3.setText(this.gracz1[2].wartosc + "");
        }
        
        if(this.gracz1[3].typ == 0){
            jLabel4.setVisible(false);
        }else{
            jLabel4.setText(this.gracz1[3].wartosc + "");
        }
        
        if(this.gracz1[4].typ == 0){
            jLabel5.setVisible(false);
        }else{
            jLabel5.setText(this.gracz1[4].wartosc + "");
        }
        
        if(this.gracz1[5].typ == 0){
            jLabel6.setVisible(false);
        }else{
            jLabel6.setText(this.gracz1[5].wartosc + "");
        }
        
        if(this.gracz1[6].typ == 0){
            jLabel7.setVisible(false);
        }else{
            jLabel7.setText(this.gracz1[6].wartosc + "");
        }
        
        //Wyświetlanie kart gracza
        /*if(this.gracz2[0].typ == 0){
            jLabel1.setVisible(false);
        }else{
            jLabel1.setText(this.gracz1[0].wartosc + "");
        }
        
        if(this.gracz2[1].typ == 0){
            jLabel2.setVisible(false);
        }else{
            jLabel2.setText(this.gracz1[1].wartosc + "");
        }
        
        if(this.gracz2[2].typ == 0){
            jLabel3.setVisible(false);
        }else{
            jLabel3.setText(this.gracz1[2].wartosc + "");
        }
        
        if(this.gracz2[3].typ == 0){
            jLabel4.setVisible(false);
        }else{
            jLabel4.setText(this.gracz1[3].wartosc + "");
        }
        
        if(this.gracz2[4].typ == 0){
            jLabel5.setVisible(false);
        }else{
            jLabel5.setText(this.gracz1[4].wartosc + "");
        }
        
        if(this.gracz2[5].typ == 0){
            jLabel6.setVisible(false);
        }else{
            jLabel6.setText(this.gracz1[5].wartosc + "");
        }
        
        if(this.gracz2[6].typ == 0){
            jLabel7.setVisible(false);
        }else{
            jLabel7.setText(this.gracz1[6].wartosc + "");
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jButton1.setText("Graj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 140, 75, 29);

        jButton2.setText("Wyjdź");
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 210, 81, 29);

        jPanel2.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel2.setLayout(null);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 60, 180, 252);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(230, 40, 180, 252);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(480, 40, 180, 252);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(720, 20, 180, 252);
        jPanel2.add(jLabel5);
        jLabel5.setBounds(810, 40, 180, 252);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(960, 20, 180, 252);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(1120, 50, 180, 252);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
